# Generated by Django 4.0 on 2023-04-20 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='likedpost', through='likes.Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
