# Generated by Django 4.0 on 2023-04-04 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='contacts.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
