# Generated by Django 4.0 on 2023-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(error_messages={'error': 'no password'}, max_length=30, null=True),
        ),
    ]
