# Generated by Django 4.0 on 2023-04-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ['-dateliked'], 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterField(
            model_name='likes',
            name='dateliked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
