# Generated by Django 4.0 on 2023-04-04 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile/user.png', upload_to='profile/')),
                ('bio', models.TextField(blank=True)),
                ('date_register', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='account.customuser')),
            ],
        ),
    ]
